[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  # Disable secrets scanning for test files and development files
  SECRETS_SCAN_OMIT_PATHS = ".excluded-from-build/**/*,.env*,test-*.js,test-*.cjs,test-*.ts,fix-*.js,setup-*.js,setup-*.cjs,update-*.js,check-*.js,execute-*.js,create-*.js,create-*.cjs,deploy-*.ps1,schema-*.cjs,scripts/**/*,public/*.html,src/pages/*.html,*RESOLUTION*.md,*SETUP*.md,*DEALERSHIP*.md,*TEST*.md,auth-*.md,supabase-*.md"

# Functions disabled - no functions directory

# Handle SPA routing
[[redirects]]
  from = "/dashboard/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/auth/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/signup"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/legal/*"
  to = "/index.html"
  status = 200

# Fallback for all other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.supabase.co; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://*.supabase.co wss://*.supabase.co; frame-src 'none';"

# Cache headers for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/favicon.*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 